### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by Crayder** [simongeilfus/SimplexNoise#1]
How would you go about seeding these functions? Besides setting a position offset I'm not sure what to do.

**Comment by simongeilfus** [comment]
Unfortunately the permutation table is static so there's no way of setting a seed other than offsetting your input. This is how I do it. Just make sure to use a floating pointer number as integers might not offset the noise properly:

``` c++
Simplex::fBm( position + vec2( 123.456f ) );
```

**Comment by Crayder** [comment]
So shuffling the permutation table is not an option, or have you tried it? Well, you'd have to shuffle half of it then copy the shuffle to both halves.
I've seen other algorithms that shuffle the permutation table.

It would'nt exactly be seeding though. Unless we shuffle it based on the given seed. Like, when you set the seed for random, technically that seed would be the seed for the permutation table.

**Comment by simongeilfus** [comment]
Yes exactly, in most code I've seen the seed used like this:

``` c++
void seed( int seed ) {
    Rand rnd( seed );
    for( ... ) permutations[i] = rnd.randInt();
}
```

**Comment by Crayder** [comment]
Yeah exactly. So have you tried shuffling the permutation table?

If not I'd gladly do it.

**Comment by simongeilfus** [comment]
I've not tried to shuffle the permutation table but according to Gustavson comment here:
https://github.com/simongeilfus/SimplexNoise/blob/master/include/Simplex.h#L164

I would say that we could definitely write a seed function in a few lines. Get new random numbers for the first 256 numbers, and copy them to the remaining 256.

We'll have to test that but probably something like this would work:

``` c++
        Rand rand( seed );
    for( size_t i = 0; i < 256; ++i ) {
        details::perm[i] = mPerms[i + 256] = rand.nextInt() & 255;
    }
```

**Comment by simongeilfus** [comment]
Let me try that!

**Comment by Crayder** [comment]
I don't think that will work the way you have it, since `rand.nextInt() & 255` could return the same value multiple times.

You would need more of a shuffle function.

**Comment by simongeilfus** [comment]
Do you think that would be an issue? I mean rand.nextInt() or rand.randInt() seems to be the best option we have? And this is how it is implemented in Cinder's Perlin noise implementation (I've actually just copy and pasted this from there).

**Comment by Crayder** [comment]
I just thought...

perm[0] must equal perm[256]
perm[1] must equal perm[257]
perm[2] must equal perm[258]
and so on...

**Comment by simongeilfus** [comment]
Yes, this is why I'm assigning to perm[i] and perm[i+256] at the same time. I just tried a few seeds and it seems to do the job... you can copy and paste that in your app ass the Simplex::details namespace is public:

``` c++
#include "cinder\Rand.h"
```

``` c++
    Rand rand( 6543 );
    for( size_t i = 0; i < 256; ++i ) {
        Simplex::details::perm[i] = Simplex::details::perm[i + 256] = rand.nextInt() & 255;
    }
```

**Comment by simongeilfus** [comment]
I'll make some more test and will probably add this as a function in the library.

**Comment by simongeilfus** [comment]
Thanks for pointing that out, it would definitely be more convenient than offsetting the noise (which works very well too but is longer to write).

**Comment by Crayder** [comment]
But, in the permutation table, each half is values from 0-255 with no repeated values. Using `rand.nextInt() & 255` you would have some repeated value, right? I'm not sure how this will affect the permutation table's use.

I was thinking (with cinder random instead)...

```
bleh(seed)
{
    // First fill it in a consecutive order
    for( size_t i = 0; i < 256; ++i ) {
        details::perm[i] = i;
    }

    // Now shuffle
    srand( seed );
    for( size_t i = 0, size_t t = 0; i < 256; ++i ) {
        int r = rand() % 256;

        t = details::perm[i];
        details::perm[i] = details::perm[i + 256] = details::perm[r];
        details::perm[r] = details::perm[r + 256] = t;
    }
}
```

**Comment by simongeilfus** [comment]
I'm not sure either how bad that would be. But we can probably add a small condition to make sure it doesn't happen...

**Comment by simongeilfus** [comment]
Ok so I've just tried making the 3 first row the same in the NoiseGallery sample :

``` c++
Simplex::details::perm[0] = Simplex::details::perm[0 + 256] = Simplex::details::perm[1] = Simplex::details::perm[1 + 256] = Simplex::details::perm[2] = Simplex::details::perm[2 + 256] = 145;
```

And I don't see any difference...

I think I'll implement this like that:

``` c++
void seed( uint32_t s ) {
    std::random_device rd;
    std::mt19937 gen( rd() );
    gen.seed( s );
    std::uniform_int_distribution<> distribution( 1, 255 );
    for( size_t i = 0; i < 256; ++i ) {
        details::perm[i] = details::perm[i + 256] = distribution( gen );
    }
}
```

**Comment by Crayder** [comment]
I can't test it at the moment, but that sounds fine.

**Comment by simongeilfus** [comment]
Yes it does!
Here you go: https://github.com/simongeilfus/SimplexNoise/commit/96988b33815149b3c98ff4fcfd8fb80872edd3f7
